spring.application.name=cloud-storage

server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}

file.storage.path=E:/data/cloud-storage/

frontend.url=${FRONTEND_URL}

cloud.aws.s3.bucket=${AWS_S3_BUCKET}


security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=36000000

spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB

spring.servlet.multipart.file-size-threshold=2MB

logging.level.root=INFO