
spring.application.name=cloud-storage

server.port=${PORT:8080}
server.address=0.0.0.0

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}



frontend.url=${FRONTEND_URL}

cloud.aws.s3.bucket=${AWS_S3_BUCKET}


security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=36000000


logging.level.root=INFO